# Generated by Django 4.2.23 on 2025-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exam_question_studentexam_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
